import { BrowserModule} from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { ScrollingModule } from '@angular/cdk/scrolling';
import { FormsModule } from '@angular/forms';
import { NgModule } from '@angular/core';
import { AppRoutingModule } from '@src/app/app-routing.module';
import { DataService } from '@src/app/services/data.service';
import { HttpClientModule, HttpHeaders } from '@angular/common/http';
import { ClickOutsideModule } from 'ng-click-outside';
import { AppComponent } from '@src/app/app.component';
import { NavbarComponent } from '@src/app/components/navbar/navbar.component';
import { Homepage } from '@src/app/components/homepage/homepage.component';
import { Loginpage } from '@src/app/components/loginpage/loginpage.component';
import { ExperiencesComponent } from '@src/app/components/pages/experiences/experiences.component';
import { TipsComponent } from '@src/app/components/pages/tips/tips.component';
import { AboutComponent } from '@src/app/components/pages/about/about.component';
import { SettingsComponent } from '@src/app/components/pages/settings/settings.component';
import { ButtonModule } from 'primeng/button';
import { ColorPickerModule } from 'primeng/colorpicker';
import { OverlayPanelModule } from 'primeng/overlaypanel';
import { DropdownModule} from 'primeng/dropdown';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';




@NgModule({
  declarations: [
    AppComponent,
    NavbarComponent,
    ExperiencesComponent,
    TipsComponent,
    AboutComponent,
    SettingsComponent,
    Homepage,
    Loginpage,
    AutoGeneratedComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
    ClickOutsideModule,
    FormsModule,
    BrowserAnimationsModule,
    ScrollingModule,
    ButtonModule,
    ColorPickerModule,
    OverlayPanelModule,
    DropdownModule
  ],
  providers: [DataService],
  bootstrap: [AppComponent]
})
export class AppModule { }
